export const ADD_TODO = "ADD_TODO";
export const TOOGLE_TODO = "TOOGLE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const MARK_COMPLETED = "MARK_COMPLETED";
export const MARK_INCOMPLETE = "MARK_INCOMPLETE";
export const FILTER_TODOS= "FILTER_TODOS";
export const MARK_ALL_COMPLETE = "MARK_ALL_COMPLETE";
export const UPDATE_SEARCH_ITEM = "UPDATE_SEARCH_ITEM";